### PR TITLE
Removing double spaces from product names

### PR DESCRIPTION
**Pull request by timjohnson-valtech**
The double spaces cause issues with testing because in some cases when double spaces are rendered the double space is converted to just a single space.  This results in some tests not being able to find the product name text when for example using something like `getByText`

### CODE REVIEW

**Review by mikefisher84 — APPROVED** [review]
👏🏻

**Comment by serhalp** [comment]
@timjohnson-valtech 

1. It looks like you didn't follow the [documented process to release a version](https://github.com/goodeggs/fake-eggs#releasing). I'm not sure what you did exactly, but your version is released, the tag is pushed, but `package.json#version` is not updated, so the next person who tries to release a version will run into an error (and your version is not on master, which is generally confusing).
2. We're working on [making this experience better](https://goodeggs.atlassian.net/wiki/spaces/ENG/pages/1794539553/Ownership+strategies+for+code+repositories) but FYI fake-eggs is owned by Developer Enablement, so ideally that team would review PRs here. Obviously there's almost no way for anyone to remember who owns what, so that's understandable – we also haven't been actually enforcing this for years, but we're working on encoding it clearly soon!
3. IMO I would prefer not to make this change. See my justification here in a previous proposed PR: https://github.com/goodeggs/fake-eggs/pull/35#pullrequestreview-340144057. I certainly am in favor of taking into account pragmatic DX concerns but I'm not sure if that applies here. Don't these React tests also break if there's a `<` in the string? `<blink>`? The reality is a product name _can contain double spaces_. I guess that means our code and the tests for our code should handle it. If that's _really difficult_ for some reason, I could be on board to remove the double spaces, to be pragmatic. But is it?

**Comment by timjohnson-valtech** [comment]
Okay I'll revert these changes.  I'll also fix the versioning issue too. We'll solve issues with this in MMA instead.

**Comment by timjohnson-valtech** [comment]
Also, I followed the instructions for creating a new version but looking back at my terminal now I see that the commit to master was rejected:

Screen Shot 2021-12-17 at 12 34 15 PM

**Comment by serhalp** [comment]
@timjohnson-valtech yeah, in the future, please make sure to follow the instructions in the README, from your branch, before merging (not from master after merging)

**Pull request merged**
